Added countdown to start of match.
HouraiTeahouse/FantasyCrescendo pull request #297
Opened 2018-07-25 08:18 UTC by LadyEbony

### Motivation and Context
- [X] Why is this change required? What problem does it solve?
James asked me.
- [ ] If it fixes an open issue, include the text `Closes #1` (where 1 would be the issue number) to your commit message.

### Types of changes
What types of changes does your code introduce? Check all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
Added a countdown UI to Stage GUI.
Added boolean variable to MatchManager, which influences input from MatchController.
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
- [ ] Describe your changes in detail.
MatchManager now begins a countdown Task before the MatchStartEvent. During that period, new MatchManager variable, isControllerLocked, is set to true, which disables input from MatchController. Once the countdown finishes, isControllerLocked is set to False and MatchStartEvent is called as usual.

If I am doing something unpleasant in the code, please tell me. Not familiar with Tasks nor this project's code standards.

2018-07-25 19:29 UTC, james7132 requested changes
A few small changes, but otherwise a fast and quick implementation.

2018-07-25 19:29 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownController.cs
> +    public float GoDuration = 1.25f;
We are aiming to play some audio while this counts down. Potential option: take in a array of AudioClips, play them to an AudioSource and use that as the base for how long to wait. Should also avoid needing to hard-code the 3 second timer.

2018-07-25 19:29 UTC, james7132 commented on Assets/Code/src/Runtime/Core/GameController.cs
> +    if (!MatchManager.Instance.isControllerLocked){
MatchController.Update is called mainly from MatchManager, where isControllerLocked is defined. I would advise just wrapping calls to it in MatchManager, not here.

2018-07-25 19:29 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownController.cs
> +    public Text TextUI;
We're trying to avoid use of normal Text objects when possible when we have TextMeshPro available. Please replace with a TextMeshProUGUI reference.

2018-07-25 19:29 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownController.cs
> +    {
Safety check: make sure that the text display object is not null.

2018-07-25 19:36 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchManager.cs
> +  public bool isControllerLocked { get; private set; }
Style: Please use uppercase properties for public properties. 

Might also be a good idea to also inverse this: IsControllerRunning, which defaults to false, set only in the RunMatch method.

2018-07-26 03:36 UTC, LadyEbony commented
Made changes requested. Check commits for all changes.

2018-07-26 08:19 UTC, james7132 requested changes
Mostly small changes to make the code higher quality. Pretty much usable with the requested changes.

2018-07-26 08:19 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownUI.cs
> +    public TextMeshProUGUI _TextUI;
Make this private, and annotate with `UnityEngine.SerializeField` instead. Same with below.

If it's private: `_textUI` vs `_TextUI`.

2018-07-26 08:19 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownUI.cs
> +            if (!_TextUI)
nit: Compare against null instead of using conversion to bool.

2018-07-26 08:19 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownUI.cs
> +        if (DisableCountdown) return;
To make sure that this does not affect non-debug builds, boolean AND with `Debug.isDebugBuild`

2018-07-26 08:19 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Events/MatchStartCountdownEvent.cs
> +public class MatchStartCountdownEvent : MatchEvent{
Quick doc comment here.

2018-07-26 08:19 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownUI.cs
> +        var timer = 3;
Default this to the length of CountdownClips.

2018-07-26 08:19 UTC, james7132 commented on Assets/Code/src/Runtime/Match/Components/MatchCountdownUI.cs
> +            await UpdateTextUI(timer.ToString(), CountdownClips[timer], 1);
Please use the length of the clips as the wait length.

2018-07-26 10:05 UTC, LadyEbony commented
Made change requests to improve code quality.

2018-07-26 10:07 UTC, james7132 approved these changes
LGTM.

2018-07-26 10:08 UTC, merged